KNOWLEDGE = [
    "Python is a dynamically typed language that supports multiple paradigms including procedural, object-oriented, and functional programming.",
    "In JavaScript, === checks both value and type, while == performs type coercion.",
    "Next.js uses file-based routing inside the app or pages directory depending on the version.",
    "REST APIs are stateless and typically use HTTP methods like GET, POST, PUT, and DELETE.",
    "Overfitting happens when a model learns noise in training data instead of general patterns.",
    "Gradient descent is an optimization algorithm used to minimize loss functions.",
    "Transformers use self-attention to process input sequences in parallel.",
    "Embeddings map discrete tokens into continuous vector spaces.",
    "The derivative represents the rate of change of a function with respect to a variable.",
    "A matrix is invertible only if its determinant is non-zero.",
    "Eigenvectors are vectors that only scale when a linear transformation is applied.",
    "Big-O notation describes the upper bound of an algorithm’s growth rate.",
    "DNS translates domain names into IP addresses.",
    "HTTP status code 404 means Not Found.",
    "WebSockets allow full-duplex communication between client and server.",
    "Load balancers distribute traffic across multiple servers.",
    "The capital of France is Paris.",
    "The Earth orbits the Sun once approximately every 365.25 days.",
    "Water boils at 100°C at standard atmospheric pressure.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "A deadlock occurs when two processes wait indefinitely for each other's resources.",
    "Memoization improves performance by caching function results.",
    "A binary search requires a sorted array.",
    "Recursion is when a function calls itself until a base case is reached."
]